# Setup
title: Solving hunger in Africa
description: >- # this means to ignore newlines until "baseurl:"
  Can se solve hunger in Africa?
baseurl: "/mADAm-2019" # the subpath of your site, e.g. /blog
url: "https://manuleo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
copyright: 'Copyright &copy; 2019 mADAm Team. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/manuleo/mADAm-2019